C#/Cadastro/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CadastrodePessoas.Models
{
    public class LoginViewModel
    {
        [Required]
        [Display(Name="Usaurio:")]
        //Atalho para criar digita prop
        public string Usuario { get; set; }
        [Display(Name = "Senha:")]
        [Required]
        [DataType(DataType.Password)]
        public string Senha { get; set; }
        [Display(Name = "Lembrar Me:")]
        public bool LembrarMe { get; set; }

    }
}

C#/Cadastro/Controllers/CadastroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CadastrodePessoas.Controllers
{
    public class CadastroController : Controller
    {
        [Authorize]
        public ActionResult CadastroPessoa()
        {
            return View();
        }
    }
}

C#/Cadastro/Controllers/ConsultaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CadastrodePessoas.Controllers
{
    public class ConsultaController : Controller
    {
        [Authorize]
        public ActionResult ConsultaPessoa()
        {
            return View();
        }
    }
}

C#/Cadastro/Controllers/ContaController.cs

using CadastrodePessoas.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace CadastrodePessoas.Controllers
{
    public class ContaController : Controller
    {
        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }
        [HttpPost]
        [AllowAnonymous]
        public ActionResult Login(LoginViewModel login,string returnUrl)
        {
          if(!ModelState.IsValid)
            {
                return View(login);
            }
            var achou = (login.Usuario == "matheus" && login.Senha == "123");

            if (achou)
            {
                FormsAuthentication.SetAuthCookie(login.Usuario, login.LembrarMe);
                if (Url.IsLocalUrl(returnUrl))
                {
                    return Redirect(returnUrl);
                }
                else
                {
                    RedirectToAction("Index", "Home");
                }
            }
            else
            {
                ModelState.AddModelError("", "Login Inválido");
            }
            return View(login);
        }
    }
}

C#/Cadastro/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Cadastro.Controllers
{
    public class HomeController : Controller
    {
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }
        [Authorize]
        public ActionResult Sobre()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

     
    }
}

C#/Cadastro/Views/Cadastro/CadastroPessoa.cshtml

@{
    ViewBag.Title = "CadastroPessoa";
}

<h2>CadastroPessoa</h2>


C#/Cadastro/Views/Consulta/ConsultaPessoa.cshtml

@{
    ViewBag.Title = "ConsultaPessoa";
}

<h2>ConsultaPessoa</h2>


C#/Cadastro/Views/Conta/Login.cshtml
@model CadastrodePessoas.Models.LoginViewModel
@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>

<div class="container">
    <div class="row">
        <h3 class="titulo">Tela de Login</h3>
    </div>
    <div class="row">
        <section id="loginForm">

            @using (Html.BeginForm("Login", "Conta", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.ValidationSummary(true,"",new {@class="text-danger" })
                <div class="form-group">
                    @Html.LabelFor(m => m.Usuario, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Usuario, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m=>m.Usuario,"", new { @class="text-danger"})
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Senha, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.PasswordFor(m => m.Senha, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Usuario, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-10 col-md-offset-2">
                        @Html.CheckBoxFor(m => m.LembrarMe)
                        @Html.LabelFor(m => m.LembrarMe)
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-10 col-md-offset-2">
                       <input type="submit" class="btn btn-success" value="Entrar" />
                    </div>
                </div>
            }
        </section>
    </div>
</div>

@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
    }

C#/Cadastro/Views/Home/Index.cshtml
<h1>Pagina inicial</h1>

C#/Cadastro/Views/Home/Sobre.cshtml
@{
    ViewBag.Title = "Sobre";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

C#/Cadastro/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Cadastro de Pessoa</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Cadastro de Pessoa", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Cadastro
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Pessoa", "CadastroPessoa", "Cadastro")</li>
                        </ul>
                    </li>

                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Consultas
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Pessoa", "ConsultaPessoa", "Consulta")</li>
                        </ul>
                    </li>

                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink("Sobre", "Sobre", "Home")</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Cadastro de Pessoa</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>