C#/CadastroUsuario/CadastroUsuario/Models/Curso.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadastroUsuario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public Nullable<int> Vagas { get; set; }
    }
}

C#/CadastroUsuario/CadastroUsuario/Models/DBModel.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadastroUsuario.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBModels : DbContext
    {
        public DBModels()
            : base("name=DBModels")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Curso> Curso { get; set; }
        public virtual DbSet<Pessoa> Pessoa { get; set; }
    }
}

C#/CadastroUsuario/CadastroUsuario/Models/DBModel.Designer.cs
// T4 code generation is enabled for model 'D:\CadastroUsuario\CadastroUsuario\Models\DBModel.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

C#/CadastroUsuario/CadastroUsuario/Models/DBModel.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

C#/CadastroUsuario/CadastroUsuario/Models/Pessoa.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadastroUsuario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pessoa
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public string Senha { get; set; }
    }
}

C#/CadastroUsuario/CadastroUsuario/Controllers/CursoController.cs
using CadastroUsuario.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CadastroUsuario.Controllers
{
    public class CursoController : Controller
    {
        // GET: Curso
        DBModels db = new DBModels();

        public ActionResult Listar()
        {
            return View(db.Curso.ToList());
        }
    }
}

C#/CadastroUsuario/CadastroUsuario/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CadastroUsuario.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

C#/CadastroUsuario/CadastroUsuario/Controllers/LoginController.cs
using CadastroUsuario.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CadastroUsuario.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Acessar(string login,string password)
        {
            DBModels db = new DBModels();
            //Criando variavel para verificar se existe um cadastro no banco
           bool acessoConfirmado= db.Pessoa.Any(u=>u.Email==login && u.Senha==password);

            if (acessoConfirmado)
            {
                return RedirectToAction("Index", "Home");
            }
           

            return RedirectToAction("Index","Login");
        }
    }
}

C#/CadastroUsuario/CadastroUsuario/Controllers/UsuarioController.cs
using CadastroUsuario.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;


namespace CadastroUsuario.Controllers
{
    public class UsuarioController : Controller
    {

        // GET: Usuario
        DBModels db = new DBModels();

        public ActionResult Listar()
        {
            

            return View(db.Pessoa.ToList());
        }
        public ActionResult Cadastrar()
        {

            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(Pessoa usuario)
        {
            db.Pessoa.Add(usuario);
            db.SaveChanges();
            return RedirectToAction("Listar");
        }
        //SO EXIBI
        public ActionResult Editar(int Id)
        {

            Pessoa usuario=db.Pessoa.Find(Id);

            return View(usuario);
        }
        //RECEBE DA TELA EDITAR
        [HttpPost]
        public ActionResult Editar(Pessoa usuario)
        {
            db.Pessoa.Add(usuario);


            //db.Usuario.AddOrUpdate(usuario) tomar cuidado
            //Manipulando
           db.Entry(usuario).State = EntityState.Modified;



            db.SaveChanges();
            return RedirectToAction("Listar");
        }

        public ActionResult Visualizar(int Id)
        {
            Pessoa usuario = db.Pessoa.Find(Id);

            return View(usuario);
        }

        public ActionResult Deletar(int Id)
        {
           

            Pessoa usuario = db.Pessoa.Find(Id);



            return View(usuario);
        }


        [HttpPost]
        public ActionResult Deletar(Pessoa usuario)
        {
            db.Pessoa.Add(usuario);

            db.Entry(usuario).State = EntityState.Deleted;

            db.SaveChanges();

            return RedirectToAction("Listar");
        }


    }
}

C#/CadastroUsuario/CadastroUsuario/Views/Curso/Listar.cshtml
@model IEnumerable<CadastroUsuario.Models.Curso>

@{
    ViewBag.Title = "Listar";
}

<h2>Listar</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Vagas)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Vagas)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

C#/CadastroUsuario/CadastroUsuario/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Home</h2>

C#/CadastroUsuario/CadastroUsuario/Views/Login/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>cessar Sistemas</title>
</head>
<body>
    <form action="/Login/Acessar" method="post">
        <div>
            <label>Login</label>
            <input type="text" name="login" value="" placeholder="Login" />
        </div>
        <div>
            <label>Senha</label>
            <input type="password" name="password" value="" placeholder="Senha" />
        </div>
        <div>
            <button type="submit">Entrar</button>
        </div>
        
       
    </form>
   
</body>
</html>

C#/CadastroUsuario/CadastroUsuario/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Principal", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Usuarios", "Listar", "Usuario", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Cursos", "Listar", "Curso", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

C#/CadastroUsuario/CadastroUsuario/Views/Usuario/Cadastrar.cshtml
@model CadastroUsuario.Models.Pessoa

@{
    ViewBag.Title = "Cadastrar";
}

<h2>Cadastrar</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pessoa</h4>
        <hr />
        
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" },required="required" })
                
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" }, required = "required" })
                
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Senha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Senha, new { htmlAttributes = new { @class = "form-control" }, required = "required" })
                
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Listar")
</div>

C#/CadastroUsuario/CadastroUsuario/Views/Usuario/Deletar.cshtml
@model CadastroUsuario.Models.Pessoa

@{
    ViewBag.Title = "Deletar";
}

<h2>Deletar</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pessoa</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Senha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Senha)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Listar", "Listar")
        </div>
    }
</div>

C#/CadastroUsuario/CadastroUsuario/Views/Usuario/Editar.cshtml
@model CadastroUsuario.Models.Pessoa

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pessoa</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Senha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Senha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Senha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

C#/CadastroUsuario/CadastroUsuario/Views/Usuario/Listar.cshtml
@model IEnumerable<CadastroUsuario.Models.Pessoa>

@{
    ViewBag.Title = "Listar";
}

<h2>Listar</h2>

<p>
    @Html.ActionLink("Novo Usuario", "Cadastrar")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Senha)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Senha)
        </td>
        <td>
            @Html.ActionLink("Editar", "Editar", new { id=item.Id }) |
            @Html.ActionLink("Visualizar", "Visualizar", new { id=item.Id }) |
            @Html.ActionLink("Deletar", "Deletar", new { id=item.Id })
        </td>
    </tr>
}

</table>

C#/CadastroUsuario/CadastroUsuario/Views/Usuario/Visualizar.cshtml
@model CadastroUsuario.Models.Pessoa

@{
    ViewBag.Title = "Visualizar";
}

<h2>Visualizar</h2>

<div>
    <h4>Pessoa</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Senha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Senha)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>